In [298]:
import numpy as np

# Inputs and outputs
inputs = np.array([[0.05], [0.10]])
inputs.shape
inputs

array([[0.05],
       [0.1 ]])

In [299]:
output = np.array([[0.01], [0.99]])
output.shape
output

array([[0.01],
       [0.99]])

In [300]:
# Initialize random weights and biases
#np.random.seed(42)  # Reproducibility
#weights = np.random.rand(1, 1)
weights = np.array([0])
weights = weights.reshape(1,1)
weights

array([[0]])

In [301]:
bias = np.array([1])
bias

array([1])

In [302]:
# Learning rates
learning_rates = [0.05, 0.5, 1.0]
iterations = 100000  # Number of iterations

# Sigmoid activation function
def sigmoid_func(x):
    return 1 / (1 + np.exp(-x))

def der (x):
    return sigmoid_func(x) * (1 - sigmoid_func(x))

for epochs in range(iterations): 
    #print(f"w{epochs}: {weights}, b{epochs}: {bias}")
    input_arr = inputs 
    weighted_sum = np.dot (input_arr, weights) + bias 
    first_output = sigmoid_func(weighted_sum) 
    
    error = first_output - output 
    total_error = np.square(np.subtract(first_output,output)) .mean() 
    #print (total_error) 
    
    first_der = error 
    second_der = der(first_output) 
    derivative = first_der * second_der
    
    t_input = inputs.T 
    final_derivative = np.dot(t_input, derivative) 
    
    #update weights 
    weights = weights - 1 * final_derivative 
    
    #update bias 
    for i in derivative: 
        bias = bias - 1 * i 
    
print(weights) 
print(bias)

[[124.58490583]]
[-9.429776]


In [304]:
pred = np.array([0.1]) 
result = np.dot(pred, weights) + bias 
res = sigmoid_func(result) 
print(res)

[0.95385463]
